version: 2
jobs:
  build1:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "a first hello"
  build2:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "a first hello"
workflows:
  version: 2
  build1_build2:
    jobs:
      - build1
      - build2



    