version: 2
jobs:
  build1:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: echo "npm starting"
      - run: npm start
  build2:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: echo "npm building"
      - run: npm run build
workflows:
  version: 2
  build1_build2:
    jobs:
      - build1
      - build2



    